---
# This file is dynamically updated by the benchmarking script
# Any modifications will be lost
apiVersion: v1
kind: Pod
metadata:
  name: all
spec:
  containers:
    - name: benchmark
      args:
        - "./benchmark-runner"
        - "--output-file"
        - "aeron-echo_c-dpdk-k8s"
        - "--message-rate"
        - "100K"
        - "--message-length"
        - "288"
        - "--iterations"
        - "60"
        - "aeron/echo-client"
